[bindings.swift]
module_name = "WiMMPublicTypes"
ffi_module_name = "WiMMPublicTypesFFI"
generate_module_map = true
[bindings.kotlin]
package_name = "org.wimm.publiccontracts"
cdylib_name = "wimm_core_bindings"
