// SPDX-License-Identifier: AGPL-3.0-or-later
import {saveTransaction,deleteTransaction,saveTransfer,confirmReconciliation,reverseFinanceAction,DomainValidationError,type P2Aggregate,type TransactionAggregate,type AccountAggregate,type CategoryAggregate,type CategoryGroupAggregate,type TransferAggregate,type FinanceInverse} from '../../packages/domain/src/index.js';
import {coreInverseRequestSchema,type UUID} from '../../packages/contracts/src/index.js';
const id=(n:number)=>`f0000000-0000-4000-8000-${String(n).padStart(12,'0')}` as UUID;
const spaceId=id(1),time='2026-10-08T12:00:00Z',context={operationId:id(100),occurredAt:'2026-10-08T14:00:00Z',generatedIds:[]};
const meta=(n:number)=>({id:id(n),spaceId,revision:1,createdAt:time,updatedAt:time});
const account:AccountAggregate={...meta(2),aggregateType:'account',name:'Giro',type:'checking',onBudget:true,archived:false};
const second={...account,...meta(3),name:'Bar'};
const group:CategoryGroupAggregate={...meta(4),aggregateType:'categoryGroup',name:'Ausgaben',kind:'expense',sortOrder:0,archived:false};
const category:CategoryAggregate={...meta(5),aggregateType:'category',name:'Lebensmittel',groupId:group.id,sortOrder:0,archived:false};
const tx:TransactionAggregate={...meta(6),aggregateType:'transaction',accountId:account.id,date:'2026-10-08',amount:-1000,kind:'normal',clearance:'uncleared',note:'Originalnotiz',splits:[{id:id(7),categoryId:category.id,amount:-1000}]};
const base:P2Aggregate[]=[account,second,group,category];
const deps={ids:{next:()=>id(90)},clock:{now:()=>time}};
const heads=(all:readonly P2Aggregate[])=>({get:(id:UUID)=>all.find(a=>a.id===id),list:()=>all});
const apply=(all:readonly P2Aggregate[],change:{aggregates:readonly P2Aggregate[]})=>{const map=new Map(all.map(a=>[a.id,a]));for(const a of change.aggregates)map.set(a.id,a);return [...map.values()];};
const observed=(change:{aggregates:readonly P2Aggregate[]})=>change.aggregates.map(a=>({id:a.id,expectedRevision:a.revision}));
export function inverseCases(){const scenarios:{name:string;all:P2Aggregate[];inverse:FinanceInverse}[]=[];
 const created=saveTransaction({spaceId,commandType:'transaction.save',expectedRevisions:[{id:tx.id,expectedRevision:0},{id:account.id,expectedRevision:1},{id:category.id,expectedRevision:1}],mutations:[{aggregate:tx}]},heads(base),deps);let all=apply(base,created);
 const undoNew={spaceId,expectedRevisions:observed(created),targets:[{id:tx.id}]};scenarios.push({name:'neue Buchung rückgängig',all,inverse:undoNew});
 const undone=reverseFinanceAction(undoNew,all,{ids:{next:()=>context.operationId},clock:{now:()=>context.occurredAt}});scenarios.push({name:'Buchung wiederholen',all:apply(all,undone),inverse:{spaceId,expectedRevisions:observed(undone),targets:[{id:tx.id,previous:tx}]}});
 scenarios.push({name:'stale Gegenbefehl',all,inverse:{...undoNew,expectedRevisions:undoNew.expectedRevisions.map((e,n)=>n===0?{...e,expectedRevision:0}:e)}});
 scenarios.push({name:'Fremdaktion',all,inverse:{...undoNew,targets:[{id:id(99)}]}});
 scenarios.push({name:'Stammdaten kein Gegenbefehl',all,inverse:{...undoNew,targets:[{id:tx.id,previous:account}]}});
 const stored=all.find(a=>a.id===tx.id) as TransactionAggregate;
 const deleted=deleteTransaction({spaceId,commandType:'transaction.delete',expectedRevisions:[{id:tx.id,expectedRevision:stored.revision},{id:account.id,expectedRevision:all.find(a=>a.id===account.id)!.revision},{id:category.id,expectedRevision:1}],mutations:[{aggregate:stored}]},heads(all),deps);
 scenarios.push({name:'gelöschte Buchung wiederherstellen',all:apply(all,deleted),inverse:{spaceId,expectedRevisions:observed(deleted),targets:[{id:tx.id,previous:stored}]}});
 const transfer:TransferAggregate={...meta(20),aggregateType:'transfer',date:tx.date,sourceAccountId:account.id,targetAccountId:second.id,sourceTransactionId:id(21),targetTransactionId:id(22),amount:2000};
 const source:TransactionAggregate={...tx,...meta(21),kind:'transfer',transferId:transfer.id,amount:-2000,splits:[]};const target={...source,...meta(22),accountId:second.id,amount:2000};
 const moved=saveTransfer({spaceId,transfer,source,target,sourceAccount:account,targetAccount:second},heads(base),deps);const transferred=apply(base,moved);
 scenarios.push({name:'Transfer vollständig rückgängig',all:transferred,inverse:{spaceId,expectedRevisions:observed(moved),targets:[{id:transfer.id},{id:source.id},{id:target.id}]}});
 const transferUndo={spaceId,expectedRevisions:observed(moved),targets:[{id:transfer.id},{id:source.id},{id:target.id}]};
 const transferUndone=reverseFinanceAction(transferUndo,transferred,{ids:{next:()=>context.operationId},clock:{now:()=>context.occurredAt}});
 scenarios.push({name:'Transfer wiederholen',all:apply(transferred,transferUndone),inverse:{spaceId,expectedRevisions:observed(transferUndone),targets:[{id:transfer.id,previous:transfer},{id:source.id,previous:source},{id:target.id,previous:target}]}});
 scenarios.push({name:'Transferseite fehlt',all:transferred,inverse:{spaceId,expectedRevisions:observed(moved),targets:[{id:transfer.id,previous:transfer}]}});
 const rec={...meta(30),aggregateType:'reconciliation' as const,accountId:account.id,statementDate:tx.date,statementBalance:tx.amount,transactionIds:[tx.id]};
 const confirmed=confirmReconciliation({spaceId,reconciliation:rec,transactions:[stored]},heads(all),deps).changeSet;
 scenarios.push({name:'Abgleich rückgängig mit ursprünglicher Clearance',all:apply(all,confirmed),inverse:{spaceId,expectedRevisions:observed(confirmed),targets:[{id:rec.id},{id:tx.id,previous:stored}]}});
 const reconciled=apply(all,confirmed);
 const recUndo={spaceId,expectedRevisions:observed(confirmed),targets:[{id:rec.id},{id:tx.id,previous:stored}]};
 const recUndone=reverseFinanceAction(recUndo,reconciled,{ids:{next:()=>context.operationId},clock:{now:()=>context.occurredAt}});
 scenarios.push({name:'Abgleich wiederholen',all:apply(reconciled,recUndone),inverse:{spaceId,expectedRevisions:observed(recUndone),targets:[{id:rec.id,previous:confirmed.aggregates.find(a=>a.id===rec.id)!},{id:tx.id,previous:confirmed.aggregates.find(a=>a.id===tx.id)!}]}});
 return scenarios.map(s=>{const request={contractVersion:1,domainSchemaVersion:1,spaceId,aggregates:s.all,expectedRevisions:s.inverse.expectedRevisions,targets:s.inverse.targets,context};let expected:unknown;try{if(!coreInverseRequestSchema.safeParse(request).success)throw new DomainValidationError('INVALID_COMMAND','Der Fachbefehl ist ungültig.');expected={contractVersion:1,status:'changed',changeSet:reverseFinanceAction(s.inverse,s.all,{ids:{next:()=>context.operationId},clock:{now:()=>context.occurredAt}})};}catch(e){if(!(e instanceof DomainValidationError))throw e;expected={contractVersion:1,status:'rejected',error:{code:e.code,message:e.message}};}return{name:`Gegenbefehl ${s.name}`,method:'reverse' as const,request,expected};});
}
