// SPDX-License-Identifier: AGPL-3.0-or-later
import { expect, test } from '@playwright/test';
for (const mobile of [false, true]) test(`Liste zuerst, Ausgabe, Erstattung, Filter und Entwurf ${mobile ? 'mobil' : 'Desktop'}`, async ({ page }) => {
  if (mobile) await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/tests/workspace.html?count=3');
  await page.getByRole('button', { name: 'Buchungen', exact: true }).click();
  await expect(page.getByRole('form', { name: 'Buchung erfassen' })).toHaveCount(0);
  await expect(page.getByRole('region', { name: 'Buchungsliste' })).toBeVisible();
  await page.getByRole('button', { name: 'Neue Buchung', exact: true }).click();
  let dialog = page.getByRole('dialog', { name: 'Neue Buchung', exact: true });
  await expect(dialog.getByLabel('Betrag', { exact: true })).toBeFocused();
  await dialog.getByLabel('Betrag', { exact: true }).fill('42,50');
  await dialog.getByRole('combobox', { name: 'Konto', exact: true }).selectOption({ label: 'Testkonto' });
  await dialog.getByRole('combobox', { name: 'Kategorie', exact: true }).selectOption({ label: 'Testkategorie' });
  await dialog.locator('summary').filter({ hasText: 'Notiz' }).click();
  await dialog.getByLabel('Notiz', { exact: true }).fill('Neue Ausgabe');
  await page.evaluate(() => window.workspaceTest.mode('quota'));
  await dialog.getByRole('button', { name: 'Lokal speichern' }).click();
  await expect(dialog.getByRole('alert')).toContainText('Speicher ist voll');
  await expect(dialog.getByLabel('Betrag', { exact: true })).toHaveValue('42,50');
  await page.evaluate(() => window.workspaceTest.mode('normal'));
  await dialog.getByRole('button', { name: 'Lokal speichern' }).click();
  await expect(dialog).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Neue Buchung', exact: true })).toBeFocused();
  expect((await page.evaluate(() => window.workspaceTest.read())).filter(entry => entry.aggregateType === 'transaction' && 'note' in entry && entry.note === 'Neue Ausgabe')).toMatchObject([{ amount: -4250 }]);
  await page.getByRole('button', { name: 'Filter', exact: true }).click();
  await page.getByLabel('Von Datum').fill('2026-10-01');
  await page.getByRole('button', { name: /^Ab .* entfernen/ }).click();
  await expect(page.getByLabel('Von Datum')).toHaveValue('');
  await page.getByRole('button', { name: 'Neue Buchung', exact: true }).click();
  dialog = page.getByRole('dialog', { name: 'Neue Buchung', exact: true });
  await dialog.getByRole('button', { name: 'Einnahme', exact: true }).click();
  await dialog.getByLabel('Betrag', { exact: true }).fill('10');
  await dialog.getByRole('combobox', { name: 'Konto', exact: true }).selectOption({ label: 'Testkonto' });
  await dialog.getByRole('combobox', { name: 'Kategorie', exact: true }).selectOption({ label: 'Testkategorie' });
  await dialog.getByRole('button', { name: 'Lokal speichern' }).click();
  expect((await page.evaluate(() => window.workspaceTest.read())).some(entry => entry.aggregateType === 'transaction' && 'amount' in entry && entry.amount === 1000)).toBe(true);
  await page.getByRole('button', { name: 'Neue Buchung', exact: true }).click();
  await page.getByLabel('Betrag', { exact: true }).fill('25');
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog', { name: 'Ungespeicherte Eingaben verwerfen?' })).toBeVisible();
  await page.getByRole('button', { name: 'Weiter bearbeiten' }).click();
  await expect(page.getByLabel('Betrag', { exact: true })).toHaveValue('25');
});

test('Konto und Anfangsbestand bleiben bei fehlgeschlagenem Batch vollständig unverändert', async ({ page }) => {
  await page.goto('/tests/workspace.html?count=3');
  await page.getByRole('button', { name: 'Konten', exact: true }).click();
  await page.getByRole('button', { name: 'Neues Konto', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Konto anlegen', exact: true });
  await dialog.getByLabel('Kontoname').fill('Neues Girokonto');
  await dialog.getByLabel('Anfangsbestand (optional)').fill('1234,56');
  const before = await page.evaluate(() => window.workspaceTest.read());
  await page.evaluate(() => window.workspaceTest.mode('partial'));
  await dialog.getByRole('button', { name: 'Konto anlegen', exact: true }).click();
  await expect(dialog.getByRole('alert')).toBeVisible();
  expect(await page.evaluate(() => window.workspaceTest.read())).toEqual(before);
  await page.evaluate(() => window.workspaceTest.mode('normal'));
  await dialog.getByRole('button', { name: 'Konto anlegen', exact: true }).click();
  await expect(dialog).toHaveCount(0);
  await page.getByRole('button', { name: 'Neues Girokonto', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Neues Girokonto', exact: true })).toBeVisible();
  await expect(page.locator('.account-balance')).toContainText('1.234,56');
  await page.getByRole('button', { name: 'Neue Buchung', exact: true }).click();
  await expect(page.getByRole('combobox', { name: 'Konto', exact: true })).not.toHaveValue('');
});
