packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds: {}
engineStrict: true
linkWorkspacePackages: false
minimumReleaseAge: 10080
saveExact: true
saveWorkspaceProtocol: true
sharedWorkspaceLockfile: true
strictDepBuilds: true
strictPeerDependencies: true
