# SPDX-License-Identifier: AGPL-3.0-or-later
[package]
name = "wimm-client-application"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
[dependencies]
wimm-contract-primitives = { path = "../contract-primitives" }
wimm-finance-core = { path = "../finance-core" }
wimm-finance-types = { path = "../finance-types" }
wimm-local-contracts = { path = "../local-contracts" }
serde.workspace = true
serde_json.workspace = true
sha2 = "=0.11.0"
uniffi = { workspace = true, optional = true }
tsify = { version = "=0.5.8", default-features = false, features = ["json"], optional = true }
wasm-bindgen = { workspace = true, optional = true }
schemars = { version = "=1.2.2", optional = true }
[features]
native-bindings = ["dep:uniffi", "wimm-finance-types/native-bindings", "wimm-local-contracts/native-bindings"]
wasm-bindings = ["dep:tsify", "dep:wasm-bindgen", "wimm-finance-types/wasm-bindings", "wimm-local-contracts/wasm-bindings"]
contract-schema = ["dep:schemars", "wimm-finance-types/contract-schema", "wimm-local-contracts/contract-schema"]
[dev-dependencies]
wimm-client-crypto = { path = "../client-crypto" }
wimm-local-dal = { path = "../local-dal", features = ["sqlite"] }
[lints]
workspace = true
