// SPDX-License-Identifier: AGPL-3.0-or-later
import { expect, it, describe } from 'vitest';
import { createAggregateMetadata, reviseAggregate, commitImportGroup, saveImportBatch, saveRule, reorderRules, applyRules, dueDates, saveSchedule, resolveOccurrence, duplicateStatus, classifyImportCandidates, importFingerprint, type DomainDependencies, type P2Aggregate, type RuleAggregate, type ScheduleAggregate, type ImportBatchAggregate, type TransactionAggregate, type ImportFingerprintAggregate } from './index.js';
let counter = 100;
const space = '00000000-0000-4000-8000-000000000001';
const deps: DomainDependencies = { ids: { next: () => `00000000-0000-4000-8000-${String(++counter).padStart(12, '0')}` }, clock: { now: () => '2026-10-05T12:00:00Z' } };
const meta = () => createAggregateMetadata(space, deps);
function setup() {
  const account = { ...meta(), aggregateType: 'account' as const, name: 'Giro', type: 'checking' as const, onBudget: true, archived: false };
  const group = { ...meta(), aggregateType: 'categoryGroup' as const, name: 'Ausgaben', kind: 'expense' as const, archived: false };
  const category = { ...meta(), aggregateType: 'category' as const, name: 'Lebensmittel', groupId: group.id, archived: false };
  const all: P2Aggregate[] = [account, group, category]; return { account, category, all };
}
const apply = (all: P2Aggregate[], change: { aggregates: readonly P2Aggregate[] }) => [...all.filter(a => !change.aggregates.some(b => b.id === a.id)), ...change.aggregates];
function schedule(accountId: string, categoryId: string): ScheduleAggregate { return { ...meta(), aggregateType: 'schedule', startDate: '2028-01-31', frequency: 'monthly', interval: 1, enabled: true, template: { accountId, amount: -100, kind: 'normal', clearance: 'uncleared', splits: [{ id: deps.ids.next(), categoryId, amount: -100 }] } }; }
function batch(accountId: string, categoryId: string, count = 1): ImportBatchAggregate { return { ...meta(), aggregateType: 'importBatch', fileHash: 'a'.repeat(64), accountId, committedRows: [], state: 'ready', rows: Array.from({ length: count }, (_, index) => ({ sourceRow: index + 1, candidate: { sourceRow: index + 1, date: '2028-01-31', amount: -100, categoryId, externalId: `id-${index}` }, decision: 'import', issues: [] })) }; }
describe('P5.4 atomare Importgruppen', () => {
  it('übernimmt höchstens 100 und setzt ohne Doppelbuchung fort', () => { const { account, category, all } = setup(); const b = batch(account.id, category.id, 205); let state = apply(all, saveImportBatch(b, all, deps)); let current = b; for (const count of [100, 200, 205]) { const change = commitImportGroup(current, state, deps)!; state = apply(state, change); current = state.find(a => a.id === b.id) as ImportBatchAggregate; expect(current.committedRows).toHaveLength(count); expect(state.filter(a => a.aggregateType === 'transaction')).toHaveLength(count); } expect(commitImportGroup(current, state, deps)).toBeNull(); expect(current.state).toBe('completed'); });
  it('blockiert ungültige Zeilen bis zum ausdrücklichen Ausschluss', () => { const { account, category, all } = setup(); const b = batch(account.id, category.id); const invalid = { ...b, rows: [{ ...b.rows[0]!, candidate: null, issues: ['Datum ungültig'] }] }; expect(() => saveImportBatch(invalid, all, deps)).toThrow('ausgeschlossen'); expect(saveImportBatch({ ...invalid, rows: [{ ...invalid.rows[0]!, decision: 'exclude' }] }, all, deps).aggregates).toHaveLength(1); });
  it('erlaubt identische echte Zahlungen nur nach bewusster Entscheidung', () => { const { account, category, all } = setup(); const first = batch(account.id, category.id); let state = apply(all, saveImportBatch(first, all, deps)); state = apply(state, commitImportGroup(first, state, deps)!); const repeated = batch(account.id, category.id); state = apply(state, saveImportBatch(repeated, state, deps)); expect(() => commitImportGroup(repeated, state, deps)).toThrow('Dublette'); const separate = reviseAggregate({ ...repeated, rows: [{ ...repeated.rows[0]!, decision: 'separate' as const }] }, deps); state = apply(state, saveImportBatch(separate, state, deps)); expect(commitImportGroup(separate, state, deps)?.aggregates.filter(a => a.aggregateType === 'transaction')).toHaveLength(1); const changed = reviseAggregate({ ...separate, rows: [{ ...repeated.rows[0]!, decision: 'separate' as const, candidate: { ...repeated.rows[0]!.candidate!, amount: -101 } }] }, deps); state = apply(state, saveImportBatch(changed, state, deps)); expect(() => commitImportGroup(changed, state, deps)).toThrow('Prüfkonflikt'); });
  it('normalisiert NFC, Leerzeichen und Kleinschreibung; Quell-IDs je Parser', () => { const row = { sourceRow: 1, date: '2028-01-31', amount: 100, payee: '  ÄPFEL  Öl ', memo: 'A\n B' } as const; expect(importFingerprint(row)).toBe(importFingerprint({ ...row, payee: 'äpfel öl', memo: 'a b' })); const f: ImportFingerprintAggregate = { ...meta(), aggregateType: 'importFingerprint', accountId: 'a', parserSource: 'ofx', externalId: '7', fingerprint: 'different', transactionId: 't', importId: 'i', sourceRow: 1 }; expect(duplicateStatus({ ...row, externalId: '7', parserSource: 'csv' }, 'a', [f])).toBe('new'); expect(duplicateStatus({ ...row, externalId: '7', parserSource: 'ofx' }, 'a', [f])).toBe('conflict'); });
  it('bewahrt vorherige Gruppe bei Fehler und fordert Konto-CAS für konkurrierende Importe', () => { const { account, category, all } = setup(); const b = batch(account.id, category.id, 101); let state = apply(all, saveImportBatch(b, all, deps)); const change = commitImportGroup(b, state, deps)!; expect(change.aggregates.find(a => a.id === account.id)?.revision).toBe(account.revision + 1); state = apply(state, change); const current = state.find(a => a.id === b.id) as ImportBatchAggregate; const invalid = reviseAggregate({ ...current, rows: current.rows.map(r => r.sourceRow === 101 ? { ...r, candidate: { ...r.candidate!, amount: Number.MAX_SAFE_INTEGER + 1 } } : r) }, deps); state = apply(state, saveImportBatch(invalid, state, deps)); expect(() => commitImportGroup(invalid, state, deps)).toThrow('sichere'); expect(state.filter(a => a.aggregateType === 'transaction')).toHaveLength(100); });
  it('weist Fremdbereich und Zwischenwertüberlauf vor jeder Änderung ab', () => { const { account, category, all } = setup(); const b = batch(account.id, category.id, 2); const bad = { ...b, rows: b.rows.map(r => ({ ...r, candidate: { ...r.candidate!, amount: Number.MAX_SAFE_INTEGER } })) }; expect(() => commitImportGroup(bad, [...all, bad], deps)).toThrow('Centbereich'); expect(() => saveImportBatch({ ...b, spaceId: deps.ids.next() }, all, deps)).toThrow('Bereich'); });
});
describe('P5.5 Regeln', () => {
  it('wertet feste Reihenfolge und Stop aus, Replay bleibt gleich', () => { const { category, all } = setup(); const a: RuleAggregate = { ...meta(), aggregateType: 'rule', order: 1, enabled: true, stopProcessing: true, conditions: [{ field: 'memo', operator: 'contains', value: 'öl' }], actions: [{ field: 'clearance', value: 'cleared' }] }; const b: RuleAggregate = { ...a, ...meta(), order: 2, actions: [{ field: 'categoryId', value: category.id }] }; const row = { sourceRow: 1, date: '2028-01-31', amount: -100, memo: 'Öl und Äpfel' } as const; const result = applyRules(row, [b, a], all, space); expect(result.applied).toEqual([a.id]); expect(result.candidate.clearance).toBe('cleared'); expect(result.candidate.categoryId).toBeUndefined(); expect(applyRules(row, [b, a], all, space)).toEqual(result); });
  it('lehnt Skripte, reconciled und fremde Kategorien ab; Umordnung umfasst alle Revisionen', () => { const { category, all } = setup(); const rule: RuleAggregate = { ...meta(), aggregateType: 'rule', order: 0, enabled: true, stopProcessing: false, conditions: [{ field: 'amount', operator: 'gte', value: -100 }], actions: [{ field: 'categoryId', value: category.id }] }; expect(saveRule(rule, all, deps).expectedRevisions).toHaveLength(2); expect(() => saveRule({ ...rule, actions: [{ field: 'script', value: 'alert(1)' }] } as never, all, deps)).toThrow('nicht erlaubt'); expect(() => saveRule({ ...rule, actions: [{ field: 'clearance', value: 'reconciled' }] } as never, all, deps)).toThrow('nicht erlaubt'); expect(() => saveRule({ ...rule, actions: [{ field: 'categoryId', value: deps.ids.next() }] }, all, deps)).toThrow('Bereich'); const second = { ...rule, ...meta(), order: 1 }; const reordered = reorderRules([second.id, rule.id], [rule, second], [...all, rule, second], deps); expect(reordered.aggregates.map(a => a.revision)).toEqual([2, 2]); expect(() => reorderRules([rule.id, rule.id], [rule, second], [...all, rule, second], deps)).toThrow('genau einmal'); });
});
describe('P5.6 Dauerzahlungen', () => {
  it('F14 bleibt am ursprünglichen Monatsendtag, auch mit Intervall und Enddatum', () => { const s = schedule('a', 'c'); expect(dueDates(s, '2028-04-30')).toEqual(['2028-01-31', '2028-02-29', '2028-03-31', '2028-04-30']); expect(dueDates({ ...s, interval: 2, endDate: '2028-04-01' }, '2028-12-31')).toEqual(['2028-01-31', '2028-03-31']); expect(dueDates({ ...s, startDate: '2027-01-31' }, '2027-03-31')).toEqual(['2027-01-31', '2027-02-28', '2027-03-31']); });
  it('prüft wöchentlich, jährlich, Schaltjahre und deaktivierte Serien', () => { const s = schedule('a', 'c'); expect(dueDates({ ...s, startDate: '2028-02-29', frequency: 'yearly' }, '2032-03-01')).toEqual(['2028-02-29', '2029-02-28', '2030-02-28', '2031-02-28', '2032-02-29']); expect(dueDates({ ...s, frequency: 'weekly', interval: 2 }, '2028-02-29')).toEqual(['2028-01-31', '2028-02-14', '2028-02-28']); expect(dueDates({ ...s, enabled: false }, '2028-03-31')).toEqual([]); expect(() => dueDates({ ...s, interval: 0 }, '2028-03-31')).toThrow('Intervall'); });
  it('Vorschläge sind rein, Bestätigung und Überspringen idempotent und revisionsgebunden', () => { const { account, category, all } = setup(); const s = schedule(account.id, category.id); let state = apply(all, saveSchedule(s, all, deps)); expect(state.filter(a => a.aggregateType === 'transaction')).toHaveLength(0); dueDates(s, '2028-03-31'); expect(state.filter(a => a.aggregateType === 'transaction')).toHaveLength(0); const change = resolveOccurrence(s, '2028-01-31', 'confirmed', state, deps)!; expect(change.aggregates.find(a => a.id === s.id)?.revision).toBe(2); state = apply(state, change); expect(resolveOccurrence(s, '2028-01-31', 'confirmed', state, deps)).toBeNull(); expect(state.filter(a => a.aggregateType === 'transaction')).toHaveLength(1); const current = state.find(a => a.id === s.id) as ScheduleAggregate; state = apply(state, resolveOccurrence(current, '2028-02-29', 'skipped', state, deps)!); expect(resolveOccurrence(current, '2028-02-29', 'skipped', state, deps)).toBeNull(); expect(() => resolveOccurrence(current, '2028-02-29', 'confirmed', state, deps)).toThrow('anders erledigt'); });
  it('ordnet einen Import ausdrücklich zu und erzeugt keine weitere Buchung', () => { const { account, category, all } = setup(); const s = schedule(account.id, category.id); let state = apply(all, saveSchedule(s, all, deps)); const b = batch(account.id, category.id); state = apply(state, saveImportBatch(b, state, deps)); state = apply(state, commitImportGroup(b, state, deps)!); const tx = state.find(a => a.aggregateType === 'transaction') as TransactionAggregate; const change = resolveOccurrence(s, '2028-01-31', 'confirmed', state, deps, tx)!; state = apply(state, change); expect(state.filter(a => a.aggregateType === 'transaction')).toHaveLength(1); expect((state.find(a => a.id === tx.id) as TransactionAggregate).scheduleOccurrenceId).toBeTruthy(); expect(resolveOccurrence(s, '2028-01-31', 'confirmed', state, deps, state.find(a => a.id === tx.id) as TransactionAggregate)).toBeNull(); });
});

it('erhält Empfänger atomar, verwendet eindeutige Aliasse und bewahrt den Quellfingerprint trotz Regel', () => {
  const { account, category, all } = setup();
  const target = { ...meta(), aggregateType: 'payee' as const, name: 'Bäckerei', aliases: ['Backhaus'], archived: false };
  const rule: RuleAggregate = { ...meta(), aggregateType: 'rule', order: 0, enabled: true, stopProcessing: false, conditions: [{ field: 'memo', operator: 'contains', value: 'Öl' }], actions: [{ field: 'payeeId', value: target.id }] };
  const b = batch(account.id, category.id, 3);
  const candidates = b.rows.map((row, i) => ({ ...row.candidate!, payee: i === 0 ? ' backhaus ' : 'Markt', memo: i === 2 ? 'Öl' : '' }));
  const ruled = applyRules(candidates[2]!, [rule], [...all, target], space).candidate;
  const planned = { ...b, rows: b.rows.map((row, i) => ({ ...row, candidate: i === 2 ? ruled : candidates[i]! })) };
  const state = apply([...all, target], saveImportBatch(planned, [...all, target], deps));
  const change = commitImportGroup(planned, state, deps)!;
  const transactions = change.aggregates.filter((a): a is TransactionAggregate => a.aggregateType === 'transaction');
  expect(transactions[0]!.payeeId).toBe(target.id);
  expect(transactions[2]!.payeeId).toBe(target.id);
  expect(change.aggregates.filter(a => a.aggregateType === 'payee')).toHaveLength(1);
  const fingerprints = change.aggregates.filter((a): a is ImportFingerprintAggregate => a.aggregateType === 'importFingerprint');
  expect(duplicateStatus(candidates[2]!, account.id, fingerprints)).toBe('duplicate');
  expect(importFingerprint(ruled)).toBe(importFingerprint(candidates[2]!));
});
it('markiert gleiche Zahlungen und Quell-ID-Konflikte innerhalb einer Datei vor der Übernahme', () => {
  const row = { sourceRow: 1, date: '2028-01-31', amount: -100, payee: 'Markt' };
  expect([...classifyImportCandidates([row, { ...row, sourceRow: 2 }], 'a', []).values()]).toEqual(['new', 'duplicate']);
  expect([...classifyImportCandidates([{ ...row, externalId: '42' }, { ...row, sourceRow: 2, amount: -101, externalId: '42' }], 'a', []).values()]).toEqual(['new', 'conflict']);
});

it('verhindert unsichere Kontosummen bei Dauerzahlungsbestätigung', () => {
  const { account, category, all } = setup(); const s = schedule(account.id, category.id);
  const state = apply(all, saveSchedule(s, all, deps));
  const existing: TransactionAggregate = { ...meta(), aggregateType: 'transaction', accountId: account.id, date: '2028-01-01', kind: 'normal', amount: -Number.MAX_SAFE_INTEGER, clearance: 'uncleared', splits: [{ id: deps.ids.next(), categoryId: category.id, amount: -Number.MAX_SAFE_INTEGER }] };
  expect(() => resolveOccurrence(s, '2028-01-31', 'confirmed', [...state, existing], deps)).toThrow('sicheren Centbereich');
  expect(resolveOccurrence(s, '2028-01-31', 'confirmed', state, deps)!.aggregates.some(a => a.id === account.id && a.revision === account.revision + 1)).toBe(true);
});
