// SPDX-License-Identifier: AGPL-3.0-or-later
import { expect, test } from '@playwright/test';
import { createVault, readAggregates } from '../helpers/local.js';
import { createAccount, navigate, openAccountAction, openBooking } from '../helpers/ui.js';
for (const touch of [false, true]) test.describe(touch ? 'Touch' : 'Tastatur', () => {
  test.use(touch ? { hasTouch: true, viewport: { width: 390, height: 844 } } : {});
  test('F03 im tatsächlichen Client und bereichsgebundene Historie mit Entwurfsschutz', async ({ page }, info) => {
    await createVault(page); await createAccount(page, 'Girokonto', '1000'); await createAccount(page, 'Bargeld', '', 'cash');
    const form = await openAccountAction(page, 'Girokonto', 'Umbuchen'); await form.getByLabel('Von', { exact: true }).selectOption({ label: 'Girokonto' }); await form.getByLabel('Nach', { exact: true }).selectOption({ label: 'Bargeld' }); await form.getByLabel('Umbuchungsbetrag').fill('200'); const save = form.getByRole('button', { name: 'Umbuchung speichern' }); if (touch) await save.tap(); else { await save.focus(); await page.keyboard.press('Enter'); } await expect(page.getByRole('dialog')).toHaveCount(0);
    await navigate(page, 'Übersicht'); await expect(page.locator('.overview-hero')).toContainText('1.000,00'); for (const label of ['Monatsausgaben', 'Monatseinnahmen']) await expect(page.locator('.overview-grid article').filter({ hasText: label })).toContainText('0,00');
    await page.getByRole('button', { name: 'Rückgängig', exact: true }).click(); await navigate(page, 'Konten'); await page.getByRole('button', { name: 'Zurück zu Konten' }).click(); await expect(page.getByRole('row').filter({ hasText: 'Girokonto' })).toContainText('1.000,00'); await page.getByRole('button', { name: 'Wiederholen', exact: true }).click(); await expect(page.getByRole('row').filter({ hasText: 'Girokonto' })).toContainText('800,00');
    await page.getByRole('button', { name: 'Haushalt anlegen', exact: true }).click(); await expect(page.getByRole('button', { name: 'Rückgängig', exact: true })).toBeDisabled(); await page.getByLabel('Bereich').selectOption({ label: 'Privater Bereich' });
    await navigate(page, 'Buchungen'); const draft = await openBooking(page); await draft.getByLabel('Betrag', { exact: true }).fill('55'); const before = await readAggregates(page); await page.keyboard.press('Escape'); await expect(page.getByRole('dialog', { name: 'Ungespeicherte Eingaben verwerfen?' })).toBeVisible(); await page.getByRole('button', { name: 'Weiter bearbeiten' }).click(); await expect(draft.getByLabel('Betrag', { exact: true })).toHaveValue('55'); expect(await readAggregates(page)).toEqual(before);
    await page.keyboard.press('Escape'); await page.getByRole('button', { name: 'Eingaben verwerfen' }).click(); await page.getByLabel('Bereich').selectOption({ label: 'Haushalt 1' }); await navigate(page, 'Übersicht'); await expect(page.locator('.hero-amount')).toHaveCount(0); await page.getByLabel('Bereich').selectOption({ label: 'Privater Bereich' }); await expect(page.locator('.overview-hero')).toContainText('1.000,00'); await expect(page.getByRole('button', { name: 'Rückgängig', exact: true })).toBeDisabled(); await page.screenshot({ path: info.outputPath('f03-bereichswechsel.png'), fullPage: true });
  });
});
