// SPDX-License-Identifier: AGPL-3.0-or-later
import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react';
import type { PlatformServices, UUID } from '@wimm/contracts';
import { moneyDecimal, type ImportBatchAggregate, type ImportDecision, type RuleAggregate, type ScheduleAggregate, type ImportCandidate } from '@wimm/domain';
import { normalizeImportRecord, MAX_IMPORT_BYTES, type CsvMapping, type ImportFormat, type PreviewRow } from '@wimm/importers';
import type { AutomationModel } from '@wimm/application';
import { cancellationForSignal } from '@wimm/browser-adapters';
import { formatMoney, displayDate } from './workspace.js';
import { today as financeToday } from './account-actions.js';
import { Button, Dialog, EmptyState } from './components.js';
import { Plus } from 'lucide-react';
import { useDraftGuard, useFormDraft } from './drafts.js';
const initialMapping: CsvMapping = { name: 'Standard', encoding: 'utf-8', separator: ';', header: true, columns: { date: 0, amount: 1, payee: 2, memo: 3, externalId: 4 }, dateFormat: 'dach', decimal: ',', thousands: '.', sign: 1 };
function errorText(error: unknown) { return error instanceof Error ? error.message : 'Die Aktion ist fehlgeschlagen.'; }
function AccountSelect({ model, value, onChange }: { model: AutomationModel; value: string; onChange: (id: string) => void }) { return <label>Konto<select required value={value} onChange={e => onChange(e.target.value)}><option value="">Auswählen</option>{model.finance.accounts.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label>; }
function CategorySelect({ model, value, onChange }: { model: AutomationModel; value: string; onChange: (id: string) => void }) { return <label>Kategorie<select required value={value} onChange={e => onChange(e.target.value)}><option value="">Auswählen</option>{model.finance.categories.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label>; }

export function ImportView({ model, platform }: { model: AutomationModel; platform: PlatformServices }) {
  const [step, setStep] = useState(0);
  const [mapping, setMapping] = useState<CsvMapping>(initialMapping); const [format, setFormat] = useState<ImportFormat>('csv');
  const [accountId, setAccount] = useState(''); const [categoryId, setCategory] = useState(''); const [file, setFile] = useState<{ name: string; bytes: Uint8Array }>();
  const [preview, setPreview] = useState<PreviewRow[]>([]); const [decisions, setDecisions] = useState<Record<number, ImportDecision>>({}); const [page, setPage] = useState(0);
  const [parsing, setParsing] = useState(false); const [hash, setHash] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const abort = useRef<AbortController | undefined>(undefined);
  const guard = useDraftGuard();
  useEffect(() => guard.registerPending('import-preview', file !== undefined || preview.length > 0 || busy), [guard, file, preview.length, busy]);
  useEffect(() => () => abort.current?.abort(), []);
  async function choose() { try { const files = await platform.chooseImportFiles({ multiple: false, maxBytes: MAX_IMPORT_BYTES, maxFiles: 1, maxTotalBytes: MAX_IMPORT_BYTES, acceptedExtensions: ['csv', 'xml', 'ofx', 'qfx'], acceptedMediaTypes: [] }); const selected = files[0]; if (!selected) return; if (selected.bytes.byteLength > MAX_IMPORT_BYTES) throw new Error('Die Datei ist größer als 25 MiB.'); setFile({ name: selected.name, bytes: selected.bytes }); setPreview([]); setStep(1); setMessage('Datei lokal ausgewählt. Bitte Zuordnung prüfen und Vorschau erstellen.'); } catch (e) { setMessage(errorText(e)); } }
  async function parse() {
    if (!file) return; setBusy(true); setParsing(true); setMessage('Datei wird lokal verarbeitet …'); abort.current = new AbortController();
    try {
      const parsed = await model.previewFile({ file, format, mapping }, cancellationForSignal(abort.current.signal));
      setHash(parsed.fileHash); setPreview([...parsed.rows]); setDecisions({}); setPage(0); setStep(2); setMessage(`${parsed.rows.length} Zeilen in der Vorschau. Noch keine Buchungen übernommen.`);
    } catch (e) { setMessage(errorText(e)); } finally { setBusy(false); setParsing(false); }
  }
  function ruleResult(row: PreviewRow) { return model.ruleResult(row, format, categoryId || undefined); }
  function candidate(row: PreviewRow): ImportCandidate | null { return ruleResult(row)?.candidate ?? null; }
  const duplicateStates = useMemo(() => model.duplicateStates(preview, decisions, format, accountId), [model, preview, decisions, format, accountId]);
  function status(row: PreviewRow) { return row.record && candidate(row) ? duplicateStates.get(row.source.sourceRow) ?? 'new' : 'invalid'; }
  async function start() {
    if (busy) return; setBusy(true);
    try {
      await model.startPreview({ accountId, categoryId, format, fileHash: hash, preview, decisions }); setPreview([]); setFile(undefined); setStep(3); setMessage('Importentscheidungen gespeichert. Übernehmen Sie nun die erste Gruppe.');
    } catch (e) { setMessage(errorText(e)); } finally { setBusy(false); }
  }
  async function next(batch: ImportBatchAggregate) { if (busy) return; abort.current = new AbortController(); setBusy(true); setMessage('Gruppe wird vorbereitet …'); try { await model.next(batch, cancellationForSignal(abort.current.signal)); setMessage('Gruppe dauerhaft gespeichert. Bereits übernommene Gruppen bleiben bei Abbruch erhalten.'); } catch (e) { setMessage(`Die Gruppe wurde nicht gespeichert. ${errorText(e)}`); } finally { setBusy(false); } }
  async function saveMapping() { try { await model.saveMapping(mapping); setMessage('Mappingvorlage im aktuellen Bereich gespeichert.'); } catch (e) { setMessage(errorText(e)); } }
  const visible = preview.slice(page * 25, page * 25 + 25);
  const invalidCount = preview.filter(row => !row.record).length;
  const duplicateCount = [...duplicateStates.values()].filter(state => state === 'duplicate' || state === 'conflict').length;
  return <section aria-label="Dateiimport"><ol className="stepper" aria-label="Importschritte">{['Datei wählen', 'Zuordnung prüfen', 'Vorschau bearbeiten', 'Übernahme bestätigen'].map((label, index) => <li key={label} aria-current={step === index ? 'step' : undefined}>{index + 1}. {label}</li>)}</ol><p className="help-text">CSV, CAMT.053, OFX und QFX werden lokal verarbeitet. Erst Ihre Bestätigung erzeugt Buchungen.</p><fieldset className="workspace-content" disabled={busy}>
    {step === 0 ? <div className="inline-form"><label>Dateiformat<select value={format} onChange={event => setFormat(event.target.value as ImportFormat)}><option value="csv">CSV</option><option value="camt053">CAMT.053</option><option value="ofx">OFX</option><option value="qfx">QFX</option></select></label><Button variant="primary" onClick={() => void choose()}>Importdatei auswählen</Button></div> : null}
    {step === 1 ? <><p>{file?.name}</p><div className="inline-form"><AccountSelect model={model} value={accountId} onChange={setAccount} /><CategorySelect model={model} value={categoryId} onChange={setCategory} /></div>
    {format === 'csv' ? <details open><summary>CSV-Zuordnung</summary><div className="inline-form"><label>Vorlage<select defaultValue="" onChange={e => { const selected = model.mappings.find(m => m.id === e.target.value); if (selected) { setMapping(selected.mapping as CsvMapping); setPreview([]); } }}><option value="">Eigene Zuordnung</option>{model.mappings.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>Vorlagenname<input value={mapping.name} onChange={e => setMapping({ ...mapping, name: e.target.value })} /></label><label>Zeichensatz<select value={mapping.encoding} onChange={e => { setMapping({ ...mapping, encoding: e.target.value as CsvMapping['encoding'] }); setPreview([]); }}><option value="utf-8">UTF-8 / BOM</option><option value="windows-1252">Windows-1252</option></select></label><label>Trennzeichen<select value={mapping.separator} onChange={e => { setMapping({ ...mapping, separator: e.target.value as CsvMapping['separator'] }); setPreview([]); }}><option value=";">Semikolon</option><option value=",">Komma</option><option value={'\t'}>Tabulator</option></select></label><label><input type="checkbox" checked={mapping.header} onChange={e => { setMapping({ ...mapping, header: e.target.checked }); setPreview([]); }} /> Kopfzeile</label>
    {(['date', 'amount', 'debit', 'credit', 'payee', 'memo', 'externalId'] as const).map(key => <label key={key}>{({ date: 'Datumsspalte', amount: 'Betragsspalte', debit: 'Sollspalte', credit: 'Habenspalte', payee: 'Empfängerspalte', memo: 'Notizspalte', externalId: 'Quell-ID-Spalte' })[key]}<input type="number" min="1" value={mapping.columns[key] === undefined ? '' : mapping.columns[key]! + 1} onChange={e => { const columns = { ...mapping.columns }; if (e.target.value === '') { if (key !== 'date') delete columns[key]; } else columns[key] = Number(e.target.value) - 1; setMapping({ ...mapping, columns }); setPreview([]); }} /></label>)}
    <label>Datumsformat<select value={mapping.dateFormat} onChange={e => { setMapping({ ...mapping, dateFormat: e.target.value as CsvMapping['dateFormat'] }); setPreview([]); }}><option value="dach">DD.MM.YYYY</option><option value="iso">YYYY-MM-DD</option></select></label><label>Dezimalzeichen<select value={mapping.decimal} onChange={e => { setMapping({ ...mapping, decimal: e.target.value as CsvMapping['decimal'] }); setPreview([]); }}><option value=",">Komma</option><option value=".">Punkt</option></select></label><label>Tausenderzeichen<select value={mapping.thousands} onChange={e => { setMapping({ ...mapping, thousands: e.target.value as CsvMapping['thousands'] }); setPreview([]); }}><option value=".">Punkt</option><option value=",">Komma</option><option value="">Keines</option></select></label><label>Vorzeichen<select value={mapping.sign} onChange={e => { setMapping({ ...mapping, sign: Number(e.target.value) as 1 | -1 }); setPreview([]); }}><option value="1">Unverändert</option><option value="-1">Umkehren</option></select></label><button type="button" onClick={() => void saveMapping()}>Vorlage speichern</button></div></details> : null}
    <div className="dialog-actions"><Button onClick={() => setStep(0)}>Andere Datei wählen</Button><button className="primary" disabled={!file || busy || !accountId || !categoryId} type="button" onClick={() => void parse()}>Vorschau erstellen</button></div></> : null}<p role="status">{message}</p>
    {step === 2 && preview.length ? <><p>{preview.length - invalidCount} gültige Zeilen · {duplicateCount} mögliche Dubletten/Konflikte · {invalidCount} Fehler</p><p>{preview.length} Zeilen · Seite {page + 1} von {Math.ceil(preview.length / 25)}</p><ul className="import-preview">{visible.map(row => <li key={row.source.sourceRow}><p><strong>Zeile {row.source.sourceRow}</strong> · {status(row) === 'conflict' ? 'Prüfkonflikt: Quell-ID mit anderem Inhalt' : status(row) === 'duplicate' ? 'Mögliche Dublette' : status(row) === 'invalid' ? 'Fehlerhaft' : 'Neu'}</p><details><summary>Originalzeile {row.source.originalSourceRow ?? row.source.sourceRow}</summary>{row.source.accountHint ? <p>Kontohinweis aus Datei: {row.source.accountHint}. Bitte oben das Zielkonto ausdrücklich auswählen.</p> : null}<pre>{row.source.cells ? JSON.stringify(row.source.cells) : JSON.stringify(row.source.fields ?? row.source.node)}</pre></details>{row.record ? <p>{row.record.date} · {formatMoney(row.record.amount)} · {row.record.payee} · {row.record.memo}{candidate(row)?.categoryId ? ` · Kategorie: ${model.finance.categories.find(c => c.id === candidate(row)?.categoryId)?.name ?? ''}` : ''}</p> : <p role="alert">{row.issues.map(i => i.message).join(' ')}</p>}{ruleResult(row)?.applied.length ? <p>Angewandte Regeln: {ruleResult(row)?.applied.map(id => (model.rules.find(r => r.id === id)?.order ?? 0) + 1).join(', ')} · Abgleich: {candidate(row)?.clearance === 'cleared' ? 'Bestätigt' : 'Offen'}</p> : null}{row.record && !candidate(row) ? <p role="alert">Eine Regel enthält eine nicht verfügbare Referenz. Bitte Regel korrigieren oder deaktivieren.</p> : null}<RowCorrection row={row} onCorrect={updated => { setPreview(rows => rows.map(r => r.source.sourceRow === row.source.sourceRow ? updated : r)); setDecisions(current => { const updatedDecisions = { ...current }; delete updatedDecisions[row.source.sourceRow]; return updatedDecisions; }); }} /><label>Entscheidung Zeile {row.source.sourceRow}<select value={decisions[row.source.sourceRow] ?? (status(row) === 'new' ? 'import' : '')} onChange={e => setDecisions({ ...decisions, [row.source.sourceRow]: e.target.value as ImportDecision })}><option value="">Bitte entscheiden</option>{row.record && status(row) !== 'conflict' ? <><option value="import">Übernehmen</option><option value="separate">Bewusst getrennte Zahlung</option></> : null}<option value="exclude">Ausdrücklich ausschließen</option></select></label></li>)}</ul><div className="dialog-actions"><button disabled={page === 0} type="button" onClick={() => setPage(page - 1)}>Vorherige Seite</button><button disabled={(page + 1) * 25 >= preview.length} type="button" onClick={() => setPage(page + 1)}>Nächste Seite</button><button className="primary" type="button" onClick={() => setStep(3)}>Übernahme prüfen</button><button type="button" onClick={() => { setPreview([]); setFile(undefined); setStep(0); }}>Vorschau verwerfen</button></div></> : null}
    {step === 2 && preview.length === 0 ? <EmptyState title="Keine Buchungen in der Datei" action={<Button onClick={() => setStep(1)}>Zuordnung prüfen</Button>}>Es wurde nichts übernommen. Prüfen Sie die Datei und ihre Zuordnung.</EmptyState> : null}
    {step === 3 && preview.length > 0 ? <section><h2>Übernahme bestätigen</h2><p>{preview.length} Zeilen für {model.finance.accounts.find(account => account.id === accountId)?.name}. {invalidCount} fehlerhafte Zeilen und {duplicateCount} mögliche Dubletten/Konflikte benötigen eine ausdrückliche Entscheidung.</p><p>Die Entscheidungen werden zuerst gespeichert. Danach übernehmen Sie Buchungen in Gruppen von bis zu 100; bestätigte Gruppen bleiben bei einer Unterbrechung erhalten.</p><div className="toolbar"><Button onClick={() => setStep(2)}>Zurück zur Vorschau</Button><Button variant="primary" onClick={() => void start()}>Entscheidungen bestätigen</Button></div></section> : null}
    <h2 className="section-title">Gespeicherte Importe</h2>{model.batches.length ? model.batches.map(batch => <article key={batch.id}><p>{batch.state === 'completed' ? 'Abgeschlossen' : batch.state === 'partial' ? 'Teilweise übernommen' : 'Bereit'} · {batch.committedRows.length} / {batch.rows.length} Zeilen bearbeitet</p>{batch.state !== 'completed' ? <><button disabled={busy} type="button" onClick={() => void next(batch)}>Fortsetzen (bis 100 Buchungen)</button><p>Sie können hier aufhören und später fortsetzen. Bereits gespeicherte Buchungen bleiben erhalten.</p><details><summary>Ausstehende Entscheidungen ändern</summary>{batch.rows.filter(r => !batch.committedRows.includes(r.sourceRow)).slice(0, 100).map(row => <label key={row.sourceRow}>Gespeicherte Zeile {row.sourceRow}<select value={row.decision} onChange={e => { const decision = e.target.value as ImportDecision; void model.editBatch(batch, batch.rows.map(r => r.sourceRow === row.sourceRow ? { ...r, decision } : r)).catch(error => setMessage(errorText(error))); }}><option value="import">Übernehmen</option><option value="separate">Bewusst getrennte Zahlung</option><option value="exclude">Ausdrücklich ausschließen</option></select></label>)}</details></> : null}</article>) : <p>Noch keine bestätigten Importe.</p>}
  </fieldset>{parsing ? <Button onClick={() => abort.current?.abort()}>Verarbeitung abbrechen</Button> : null}</section>;
}
function RowCorrection({ row, onCorrect }: { row: PreviewRow; onCorrect: (row: PreviewRow) => void }) {
  const [date, setDate] = useState(row.record?.date ?? ''); const [amount, setAmount] = useState(row.record ? moneyDecimal(row.record.amount) : ''); const [memo, setMemo] = useState(row.record?.memo ?? row.raw?.memo ?? ''); const [payee, setPayee] = useState(row.record?.payee ?? row.raw?.payee ?? ''); const [externalId, setExternalId] = useState(row.record?.externalId ?? row.raw?.externalId ?? ''); const [error, setError] = useState('');
  function correct(e: FormEvent) { e.preventDefault(); const normalized = normalizeImportRecord({ sourceRow: row.source.sourceRow, date, amount, currency: 'EUR', payee, memo, externalId }); if (!normalized.record) { setError(normalized.issues.map(i => i.message).join(' ')); return; } onCorrect({ ...row, record: normalized.record, issues: [] }); setError(''); }
  return <details><summary>Zeile korrigieren</summary><form className="inline-form" onSubmit={correct}><label>Korrigiertes Datum<input type="date" value={date} onChange={e => setDate(e.target.value)} required /></label><label>Korrigierter Betrag (Dezimalpunkt)<input inputMode="decimal" value={amount} onChange={e => setAmount(e.target.value)} required /></label><label>Korrigierter Empfänger<input value={payee} onChange={e => setPayee(e.target.value)} /></label><label>Korrigierte Quell-ID<input value={externalId} onChange={e => setExternalId(e.target.value)} /></label><label>Korrigierte Notiz<input value={memo} onChange={e => setMemo(e.target.value)} /></label><button type="submit">Korrektur prüfen</button>{error ? <p role="alert">{error}</p> : null}</form></details>;
}

const fieldLabels = { memo: 'Verwendungszweck', payee: 'Empfänger', amount: 'Betrag', date: 'Datum' } as const;
const operatorLabels = { contains: 'enthält', equals: 'ist gleich', gte: 'ist mindestens', lte: 'ist höchstens' } as const;
const frequencyLabels = { weekly: 'Wöchentlich', monthly: 'Monatlich', yearly: 'Jährlich' } as const;
function describeRule(rule: RuleAggregate, model: AutomationModel) {
  const conditions = rule.conditions.map(condition => `${fieldLabels[condition.field]} ${operatorLabels[condition.operator]} ${condition.field === 'amount' ? formatMoney(condition.value as number) : condition.value}`).join(' und ');
  const actions = rule.actions.map(action => action.field === 'categoryId' ? `Kategorie „${model.finance.allCategories.find(category => category.id === action.value)?.name ?? 'Nicht mehr verfügbar'}“ setzen` : action.field === 'payeeId' ? `Empfänger „${model.finance.allPayees.find(payee => payee.id === action.value)?.name ?? 'Nicht mehr verfügbar'}“ setzen` : `Status „${action.value === 'cleared' ? 'Bestätigt' : 'Offen'}“ setzen`).join(', ');
  return `Wenn ${conditions}, dann ${actions}.`;
}
export function AutomationView({ model, section = 'rules' }: { readonly model: AutomationModel; readonly section?: 'rules' | 'schedules' }) {
  const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const working = useRef(false);
  const [rule, setRule] = useState<RuleAggregate | 'new'>(); const [schedule, setSchedule] = useState<ScheduleAggregate | 'new'>(); const [removing, setRemoving] = useState<RuleAggregate>();
  async function run(action: () => Promise<void>) { if (working.current) return; working.current = true; setBusy(true); setMessage(''); try { await action(); setMessage('Lokal gespeichert.'); } catch (error) { setMessage(errorText(error)); } finally { working.current = false; setBusy(false); } }
  const [today, setToday] = useState(financeToday);
  useEffect(() => {
    const update = () => setToday(financeToday());
    const timer = setInterval(update, 60_000);
    window.addEventListener('focus', update);
    document.addEventListener('visibilitychange', update);
    return () => { clearInterval(timer); window.removeEventListener('focus', update); document.removeEventListener('visibilitychange', update); };
  }, []);
  const ordered = [...model.rules].sort((a, b) => a.order - b.order || a.id.localeCompare(b.id));
  return <section><p role="status">{message}</p>{section === 'rules' ? <>
    <div className="toolbar"><Button variant="primary" icon={Plus} onClick={() => setRule('new')}>Neue Regel</Button></div><p className="help-text">Regeln ordnen importierte Buchungen in dieser Reihenfolge zu. Sie erzeugen keine Zahlungen.</p>
    {ordered.length === 0 ? <EmptyState title="Noch keine Regeln">Mit einer Regel können Sie wiederkehrende Empfänger oder Verwendungszwecke automatisch einer Kategorie zuordnen.</EmptyState> : <ul className="plain-list">{ordered.map((entry, index) => <li key={entry.id}><span>{index + 1}. {describeRule(entry, model)}<small>{entry.enabled ? 'Aktiv' : 'Pausiert'} · {entry.stopProcessing ? 'Danach keine weiteren Regeln anwenden' : 'Weitere Regeln anwenden'}</small></span><div className="list-actions"><Button disabled={busy} onClick={() => setRule(entry)}>Regel bearbeiten</Button><Button variant="quiet" disabled={busy} onClick={() => void run(() => model.toggleRule(entry))}>{entry.enabled ? 'Regel deaktivieren' : 'Regel aktivieren'}</Button><Button variant="quiet" disabled={busy || index === 0} onClick={() => void run(() => { const ids = ordered.map(item => item.id); [ids[index - 1], ids[index]] = [ids[index]!, ids[index - 1]!]; return model.order(ids); })}>Nach oben</Button><Button variant="danger" disabled={busy} onClick={() => setRemoving(entry)}>Regel löschen</Button></div></li>)}</ul>}
  </> : <>
    <div className="toolbar"><Button variant="primary" icon={Plus} onClick={() => setSchedule('new')}>Neue Dauerzahlung</Button></div><p className="help-text">Fällige Vorschläge verändern kein Guthaben. Erst „Zahlung bestätigen“ bucht; eine importierte Zahlung können Sie ausdrücklich zuordnen.</p>
    {model.schedules.length === 0 ? <EmptyState title="Noch keine Dauerzahlungen">Planen Sie wiederkehrende Zahlungen. Die App erinnert Sie mit Vorschlägen, ohne automatisch zu buchen.</EmptyState> : model.schedules.map(entry => <article className="schedule-entry" key={entry.id}><div className="section-heading"><h2>{entry.template.note || 'Dauerzahlung'}</h2><strong className="money">{formatMoney(entry.template.amount)}</strong></div><p className="help-text">{frequencyLabels[entry.frequency]} · Intervall {entry.interval} · Ab {displayDate(entry.startDate)} · {entry.enabled ? 'Aktiv' : 'Pausiert'}</p><div className="toolbar"><Button disabled={busy} onClick={() => setSchedule(entry)}>Dauerzahlung bearbeiten</Button><Button variant="quiet" disabled={busy} onClick={() => void run(() => model.toggleSchedule(entry))}>{entry.enabled ? 'Dauerzahlung deaktivieren' : 'Dauerzahlung aktivieren'}</Button></div>{entry.enabled ? model.pendingOccurrences(entry, today).slice(0, 50).map(date => <Occurrence key={date} schedule={entry} date={date} model={model} run={run} />) : null}</article>)}
  </>}
    {rule === undefined ? null : <Dialog title={rule === 'new' ? 'Regel anlegen' : 'Regel bearbeiten'} busy={busy} onClose={() => setRule(undefined)}><RuleForm model={model} previous={rule === 'new' ? undefined : rule} submit={action => void run(async () => { await action(); setRule(undefined); })} />{message ? <p role="alert">{message}</p> : null}</Dialog>}
    {schedule === undefined ? null : <Dialog title={schedule === 'new' ? 'Dauerzahlung anlegen' : 'Dauerzahlung bearbeiten'} busy={busy} onClose={() => setSchedule(undefined)}><ScheduleForm model={model} previous={schedule === 'new' ? undefined : schedule} submit={action => void run(async () => { await action(); setSchedule(undefined); })} />{message ? <p role="alert">{message}</p> : null}</Dialog>}
    {removing === undefined ? null : <Dialog title="Regel löschen?" busy={busy} onClose={() => setRemoving(undefined)}><p>{describeRule(removing, model)} Bestehende Buchungen bleiben unverändert.</p><Button variant="danger" disabled={busy} onClick={() => void run(async () => { await model.removeRule(removing); setRemoving(undefined); })}>Regel löschen bestätigen</Button>{message ? <p role="alert">{message}</p> : null}</Dialog>}
  </section>;
}
function RuleForm({ model, previous, submit }: { readonly model: AutomationModel; readonly previous?: RuleAggregate | undefined; readonly submit: (action: () => Promise<void>) => void }) {
  const form = useRef<HTMLFormElement>(null); useFormDraft(form);
  const conditionSource = previous?.conditions[0]; const actionSource = previous?.actions[0];
  const [field, setField] = useState<RuleAggregate['conditions'][number]['field']>(conditionSource?.field ?? 'memo'); const [operator, setOperator] = useState<RuleAggregate['conditions'][number]['operator']>(conditionSource?.operator ?? 'contains'); const [condition, setCondition] = useState(conditionSource === undefined ? '' : conditionSource.field === 'amount' ? moneyDecimal(conditionSource.value as number) : String(conditionSource.value));
  const [actionField, setActionField] = useState<'categoryId' | 'payeeId' | 'clearance'>(actionSource?.field ?? 'categoryId'); const [actionValue, setActionValue] = useState(actionSource?.value ?? ''); const [stop, setStop] = useState(previous?.stopProcessing ?? true);
  function save(event: FormEvent) { event.preventDefault(); submit(() => model.ruleInput({ field, operator, condition, actionField, actionValue, stop }, previous)); }
  return <form ref={form} className="inline-form" onSubmit={save}><label>Bedingungsfeld<select value={field} onChange={event => { setField(event.target.value as typeof field); setOperator(event.target.value === 'amount' || event.target.value === 'date' ? 'equals' : 'contains'); }}>{Object.entries(fieldLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Vergleich<select value={operator} onChange={event => setOperator(event.target.value as typeof operator)}><option value="equals">Gleich</option>{field === 'memo' || field === 'payee' ? <option value="contains">Enthält</option> : <><option value="gte">Mindestens</option><option value="lte">Höchstens</option></>}</select></label><label>Bedingungswert<input autoFocus required value={condition} onChange={event => setCondition(event.target.value)} /></label><label>Regelaktion<select value={actionField} onChange={event => { setActionField(event.target.value as typeof actionField); setActionValue(''); }}><option value="categoryId">Kategorie setzen</option><option value="payeeId">Empfänger setzen</option><option value="clearance">Abgleichstatus setzen</option></select></label>{actionField === 'categoryId' ? <CategorySelect model={model} value={actionValue} onChange={setActionValue} /> : <label>Aktionswert<select required value={actionValue} onChange={event => setActionValue(event.target.value)}><option value="">Auswählen</option>{actionField === 'clearance' ? <><option value="uncleared">Offen</option><option value="cleared">Bestätigt</option></> : model.finance.payees.map(payee => <option key={payee.id} value={payee.id}>{payee.name}</option>)}</select></label>}<label><input type="checkbox" checked={stop} onChange={event => setStop(event.target.checked)} /> Folgeauswertung stoppen</label><button type="submit">{previous ? 'Regel ändern' : 'Regel anlegen'}</button></form>;
}
function ScheduleForm({ model, previous, submit }: { readonly model: AutomationModel; readonly previous?: ScheduleAggregate | undefined; readonly submit: (action: () => Promise<void>) => void }) {
  const form = useRef<HTMLFormElement>(null); useFormDraft(form);
  const [account, setAccount] = useState(previous?.template.accountId ?? ''); const [category, setCategory] = useState(previous?.template.splits[0]?.categoryId ?? ''); const [amount, setAmount] = useState(previous ? moneyDecimal(previous.template.amount) : ''); const [start, setStart] = useState(previous?.startDate ?? ''); const [end, setEnd] = useState(previous?.endDate ?? ''); const [frequency, setFrequency] = useState<ScheduleAggregate['frequency']>(previous?.frequency ?? 'monthly'); const [interval, setInterval] = useState(String(previous?.interval ?? 1)); const [note, setNote] = useState(previous?.template.note ?? '');
  function save(event: FormEvent) { event.preventDefault(); submit(() => model.scheduleInput({ accountId: account, categoryId: category, amount, start, end, frequency, interval, note }, previous)); }
  return <form ref={form} className="inline-form" onSubmit={save}><AccountSelect model={model} value={account} onChange={setAccount} /><CategorySelect model={model} value={category} onChange={setCategory} /><label>Dauerzahlungsbetrag<input inputMode="decimal" required value={amount} onChange={event => setAmount(event.target.value)} /></label><label>Erste Fälligkeit<input type="date" required value={start} onChange={event => setStart(event.target.value)} /></label><label>Letzte Fälligkeit<input type="date" value={end} onChange={event => setEnd(event.target.value)} /></label><label>Rhythmus<select value={frequency} onChange={event => setFrequency(event.target.value as typeof frequency)}>{Object.entries(frequencyLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Intervall<input type="number" min="1" required value={interval} onChange={event => setInterval(event.target.value)} /></label><label>Dauerzahlungsnotiz<input value={note} onChange={event => setNote(event.target.value)} /></label><button type="submit">{previous ? 'Dauerzahlung ändern' : 'Dauerzahlung anlegen'}</button></form>;
}

function Occurrence({ schedule, date, model, run }: { schedule: ScheduleAggregate; date: string; model: AutomationModel; run: (action: () => Promise<void>) => Promise<void> }) {
  const [transactionId, setTransaction] = useState<UUID>('');
  return <div className="inline-form"><p>Fällig: {displayDate(date)}</p><button type="button" onClick={() => void run(() => model.occurrence(schedule, date, 'confirmed'))}>Zahlung bestätigen</button><button type="button" onClick={() => void run(() => model.occurrence(schedule, date, 'skipped'))}>Fälligkeit überspringen</button><label>Importierte Zahlung<select value={transactionId} onChange={e => setTransaction(e.target.value)}><option value="">Auswählen</option>{model.finance.transactions.filter(t => t.importReference && !t.scheduleOccurrenceId && t.accountId === schedule.template.accountId).map(t => <option key={t.id} value={t.id}>{t.date} · {formatMoney(t.amount)} · {t.note}</option>)}</select></label><button disabled={!transactionId} type="button" onClick={() => void run(() => model.occurrence(schedule, date, 'confirmed', transactionId))}>Import zuordnen</button></div>;
}
