# SPDX-License-Identifier: AGPL-3.0-or-later
[package]
name = "wimm-dal-proof"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
diesel = { version = "=2.3.13", default-features = false, features = ["sqlite", "32-column-tables"] }
sea-query = { version = "=1.0.2", default-features = false, features = ["derive", "backend-sqlite"] }
serde.workspace = true
serde_json.workspace = true

[target.'cfg(not(target_family = "wasm"))'.dependencies]
libsqlite3-sys = { version = "=0.38.2", features = ["bundled"] }
pq-sys = { version = "=0.7.6", features = ["bundled"], optional = true }
mysqlclient-sys = { version = "=0.5.2", features = ["bundled"], optional = true }

[target.'cfg(target_family = "wasm")'.dependencies]
sqlite-wasm-rs = "=0.5.5"
sqlite-wasm-vfs = "=0.2.0"
wasm-bindgen.workspace = true
wasm-bindgen-futures = "=0.4.79"

[features]
postgres-build = ["diesel/postgres", "dep:pq-sys"]
mysql-build = ["diesel/mysql", "dep:mysqlclient-sys"]

[lints]
workspace = true
